# Generated by Django 4.1.5 on 2023-01-31 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='いつから')),
                ('end_date', models.DateField(verbose_name='いつまで')),
                ('comment', models.CharField(blank=True, max_length=500, null=True, verbose_name='コメント')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
                ('delta', models.IntegerField(verbose_name='日数')),
            ],
        ),
    ]
